-- =============================================================================
-- db/init/schema.sql — Fintel database schema
-- =============================================================================
-- Runs automatically on first `docker compose up` when the postgres volume
-- is empty. Never runs again unless you `docker compose down -v`.
--
-- Why Postgres over flat CSV files:
--   Multiple services (pipeline, notebook, API) can read the same data
--   concurrently without file locking. SQL queries run EDA directly on
--   the database without loading entire CSVs into memory.

-- ── Filings ───────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS raw_filings (
    id               SERIAL PRIMARY KEY,
    ticker           VARCHAR(10)  NOT NULL,
    form_type        VARCHAR(10)  NOT NULL,
    filing_date      DATE         NOT NULL,
    accession_number VARCHAR(50)  UNIQUE,
    pulled_at        TIMESTAMP    DEFAULT NOW(),
    token_count_raw  INTEGER,
    source_url       TEXT,
    CONSTRAINT uq_filing UNIQUE (ticker, form_type, filing_date)
);

-- ── Cleaned sentences ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS sentences (
    id               SERIAL PRIMARY KEY,
    ticker           VARCHAR(10)  NOT NULL,
    form_type        VARCHAR(10)  NOT NULL,
    filing_date      DATE         NOT NULL,
    sentence_idx     INTEGER      NOT NULL,
    sentence         TEXT         NOT NULL,
    token_count      INTEGER,
    CONSTRAINT uq_sentence UNIQUE (ticker, filing_date, sentence_idx)
);

CREATE INDEX IF NOT EXISTS idx_sentences_ticker      ON sentences(ticker);
CREATE INDEX IF NOT EXISTS idx_sentences_filing_date ON sentences(filing_date);

-- ── Auto labels ───────────────────────────────────────────────────────────────
-- Generated by FinBERT. label: positive / neutral / negative
CREATE TABLE IF NOT EXISTS labels_auto (
    id               SERIAL PRIMARY KEY,
    ticker           VARCHAR(10)  NOT NULL,
    form_type        VARCHAR(10)  NOT NULL,
    filing_date      DATE         NOT NULL,
    sentence_idx     INTEGER      NOT NULL,
    label            VARCHAR(10)  NOT NULL,
    confidence       FLOAT        NOT NULL,
    score_positive   FLOAT,
    score_neutral    FLOAT,
    score_negative   FLOAT,
    model_version    VARCHAR(50)  DEFAULT 'ProsusAI/finbert',
    labelled_at      TIMESTAMP    DEFAULT NOW(),
    CONSTRAINT uq_auto_label UNIQUE (ticker, filing_date, sentence_idx)
);

CREATE INDEX IF NOT EXISTS idx_labels_auto_ticker ON labels_auto(ticker);
CREATE INDEX IF NOT EXISTS idx_labels_auto_label  ON labels_auto(label);

-- ── Manual labels ─────────────────────────────────────────────────────────────
-- Subset annotated by hand for Cohen's kappa quality check
CREATE TABLE IF NOT EXISTS labels_manual (
    id               SERIAL PRIMARY KEY,
    ticker           VARCHAR(10)  NOT NULL,
    filing_date      DATE         NOT NULL,
    sentence_idx     INTEGER      NOT NULL,
    label_auto       VARCHAR(10)  NOT NULL,
    label_manual     VARCHAR(10),
    confidence       FLOAT,
    annotated_at     TIMESTAMP,
    CONSTRAINT uq_manual_label UNIQUE (ticker, filing_date, sentence_idx)
);

-- ── Annotation agreement ──────────────────────────────────────────────────────
-- Stores Cohen's kappa score between auto and manual labels
CREATE TABLE IF NOT EXISTS annotation_agreement (
    id               SERIAL PRIMARY KEY,
    computed_at      TIMESTAMP    DEFAULT NOW(),
    kappa            FLOAT        NOT NULL,
    observed_agree   FLOAT        NOT NULL,
    n_samples        INTEGER      NOT NULL,
    gate_pass        BOOLEAN      NOT NULL,
    per_class_json   JSONB,
    notes            TEXT
);

-- ── Prices ────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS prices (
    id               SERIAL PRIMARY KEY,
    ticker           VARCHAR(10)  NOT NULL,
    date             DATE         NOT NULL,
    open             FLOAT,
    high             FLOAT,
    low              FLOAT,
    close            FLOAT        NOT NULL,
    volume           BIGINT,
    return_1d        FLOAT,
    is_outlier       BOOLEAN      DEFAULT FALSE,
    CONSTRAINT uq_price UNIQUE (ticker, date)
);

CREATE INDEX IF NOT EXISTS idx_prices_ticker ON prices(ticker);
CREATE INDEX IF NOT EXISTS idx_prices_date   ON prices(date);

-- ── Forward returns ───────────────────────────────────────────────────────────
-- 5-day return after each filing date — the prediction target
CREATE TABLE IF NOT EXISTS forward_returns (
    id               SERIAL PRIMARY KEY,
    ticker           VARCHAR(10)  NOT NULL,
    filing_date      DATE         NOT NULL,
    return_start     DATE         NOT NULL,
    return_end       DATE         NOT NULL,
    forward_return   FLOAT        NOT NULL,
    return_label     VARCHAR(10)  NOT NULL,
    n_days           INTEGER      NOT NULL,
    CONSTRAINT uq_fwd_return UNIQUE (ticker, filing_date, n_days)
);

-- ── Macro indicators ──────────────────────────────────────────────────────────
-- CPI, GDP, VIX, yield curve etc. from FRED
CREATE TABLE IF NOT EXISTS macro (
    id               SERIAL PRIMARY KEY,
    series_name      VARCHAR(30)  NOT NULL,
    date             DATE         NOT NULL,
    value            FLOAT,
    CONSTRAINT uq_macro UNIQUE (series_name, date)
);

CREATE INDEX IF NOT EXISTS idx_macro_series ON macro(series_name);
CREATE INDEX IF NOT EXISTS idx_macro_date   ON macro(date);

-- ── Analysis results ──────────────────────────────────────────────────────────
-- Stores output of each EDA experiment as JSON
CREATE TABLE IF NOT EXISTS analysis_results (
    id               SERIAL PRIMARY KEY,
    run_at           TIMESTAMP    DEFAULT NOW(),
    experiment       VARCHAR(50)  NOT NULL,
    result_json      JSONB        NOT NULL
);

-- ── Data quality ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS data_quality (
    id                       SERIAL PRIMARY KEY,
    ticker                   VARCHAR(10) NOT NULL,
    form_type                VARCHAR(10),
    filing_date              DATE,
    token_count_raw          INTEGER,
    token_count_clean        INTEGER,
    boilerplate_removed_pct  FLOAT,
    n_sentences              INTEGER,
    missing_days_pct         FLOAT,
    outlier_count            INTEGER,
    checked_at               TIMESTAMP DEFAULT NOW()
);

-- ── Train / val / test splits ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS splits (
    id               SERIAL PRIMARY KEY,
    ticker           VARCHAR(10) NOT NULL,
    filing_date      DATE        NOT NULL,
    split            VARCHAR(10) NOT NULL,
    CONSTRAINT uq_split UNIQUE (ticker, filing_date)
);